spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    username: root
    password: root
    url: jdbc:mysql://188.131.254.195/demo01?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
